---
- name: jtprogru.grafanaoss | include OS-specific variables.
  ansible.builtin.include_vars: RedHat.yaml

- name: jtprogru.grafanaoss | add grafana repo
  ansible.builtin.template:
    url: "{{ __grafanaoss_gpgkey_url }}"
    state: present
  when: grafanaoss_installation_type == 'repo'

- name: jtprogru.grafanaoss | add repository for yum
  ansible.builtin.yum_repository:
    repo: "{{ __grafanaoss_repository }}"
    state: present
    filename: grafanaoss
  when: grafanaoss_installation_type == 'repo'

- name: jtprogru.grafanaoss | install grafana from repository
  ansible.builtin.yum:
    name: "{{ __grafanaoss_package_name }}"
    state: present
  when: grafanaoss_installation_type == 'repo'
  notify:
    - restart grafana-server
