---
- name: Grafanaoss | restart grafana-server
  ansible.builtin.systemd:
    name: grafana-server
    state: restarted
    daemon_reload: true
  listen: restart grafana

- name: Grafanaoss | start grafana-server
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true
  listen: start grafana
